CREATE SCHEMA messenger_adapter;
create sequence messenger_adapter.user_id_seq;


create table messenger_adapter.messengers
(
    id     integer generated by default as identity
        constraint messengers_pk
            primary key,
    name   varchar(50)  not null,
    active boolean,
    route  varchar(255) not null
);

create table messenger_adapter.users
(
    id           integer generated by default as identity
        constraint users_pk
            primary key,
    phone_number varchar(20) not null unique, -- в настоящей базе данных нет ограничения UNIQUE
    fio          varchar(255),
    nickname     json -- в оригинальной базке тип json
);

create unique index users_phone_number_uindex
    on messenger_adapter.users (phone_number);

create table messenger_adapter.bots
(
    id           integer generated by default as identity
        constraint bots_pk
            primary key,
    messenger_id integer
        constraint bots_messengers_null_fk
            references messenger_adapter.messengers,
    bot_name     varchar(100) not null,
    credentials  text
);

create table messenger_adapter.message
(
    id              bigint generated by default as identity
        constraint message_pk
            primary key,
    text            text,
    media           text,
    file_name       varchar(50),
    bot_id          integer
        constraint message_bots_null_fk
            references messenger_adapter.bots,
    to_phone_number varchar(20)
        constraint message_user_null_fk
            references messenger_adapter.users (phone_number),
    status          varchar(30),
    proc_note       varchar(255),
    title           varchar(256),
    footer          varchar(255),
    request_id      varchar(255)
);



